import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* make some dummy content for my starterkit */}
      <div>
        <h1>My Next.js Starterkit</h1>
        <p>This is a starterkit for Next.js projects. It includes the following:</p>
        <ul>
          <li>Typescript</li>
          <li>SCSS</li>
          <li>Inter font</li>
          <li>Primary layout</li>
          <li>Global styles</li>
          <li>Global SCSS</li>
        </ul>
        <p>
          This is a good starting point for new projects. It includes a primary layout component,
          global styles, and a global SCSS file.
        </p>
      </div>
    </>
  );
}

